# Generated by Django 5.2.4 on 2025-08-19 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementidea',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='improvementidea',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('collection', 'Сбор голосов'), ('pending', 'На рассмотрении'), ('approved', 'Одобрен'), ('rejected', 'Отклонен'), ('implemented', 'Реализован')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
