# Generated by Django 5.2.4 on 2025-08-19 09:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов'), django.core.validators.MaxLengthValidator(100, message='Максимум 100 символов')], verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Описание')),
                ('proposed_solution', models.TextField(verbose_name='Предлагаемое решение')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='idea_images/', verbose_name='Изображение')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На рассмотрении'), ('approved', 'Одобрен'), ('rejected', 'Отклонен'), ('implemented', 'Реализован')], default='draft', max_length=20, verbose_name='Статус')),
                ('category', models.CharField(choices=[('transport', 'Транспорт'), ('infrastructure', 'Инфраструктура'), ('tourism', 'Туризм'), ('culture', 'Культура'), ('education', 'Образование'), ('health', 'Здоровье'), ('environment', 'Экология'), ('culture', 'Культура'), ('security', 'Безопасность'), ('leisure', 'Досуг'), ('other', 'Другое')], max_length=20, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Идея улучшения',
                'verbose_name_plural': 'Идеи улучшений',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IdeaVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'Голос за'), ('down', 'Голос против')], max_length=10, verbose_name='Тип голоса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.improvementidea', verbose_name='Идея')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.improvementidea', verbose_name='Идея')),
            ],
        ),
    ]
