name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "Starting deployment..."
          
          # Переходим в директорию проекта
          cd /home/novaya-lyada/novaya-lyada
          
          # Останавливаем сервисы
          echo "Stopping services..."
          sudo systemctl stop novaya-lyada novaya-lyada-celery novaya-lyada-celerybeat
          
          # Обновляем код
          echo "Updating code..."
          git fetch origin
          git reset --hard origin/main
          
          # Активируем виртуальное окружение
          source venv/bin/activate
          
          # Обновляем зависимости
          echo "Installing dependencies..."
          pip install -r requirements.txt
          
          # Выполняем миграции
          echo "Running migrations..."
          python manage.py migrate --noinput
          
          # Собираем статические файлы
          echo "Collecting static files..."
          python manage.py collectstatic --noinput
          
          # Проверяем права доступа
          sudo chown -R novaya-lyada:novaya-lyada /home/novaya-lyada/novaya-lyada
          
          # Запускаем сервисы
          echo "Starting services..."
          sudo systemctl start novaya-lyada-celerybeat
          sudo systemctl start novaya-lyada-celery
          sudo systemctl start novaya-lyada
          
          # Перезагружаем Nginx
          echo "Reloading Nginx..."
          sudo systemctl reload nginx
          
          # Проверяем статус
          echo "Checking service status..."
          sudo systemctl status novaya-lyada novaya-lyada-celery novaya-lyada-celerybeat
          
          echo "Deployment completed successfully!"
